# Generated by Django 5.1.7 on 2025-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='encrypted_password',
            new_name='password',
        ),
    ]
