# Generated by Django 5.1.7 on 2025-03-10 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_encrypted_password_passwordentry_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_master_password', models.CharField(max_length=255, verbose_name='Зашифрованный мастер-пароль')),
                ('encryption_key', models.CharField(max_length=255, verbose_name='Ключ шифрования для мастер-пароля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер-пароль',
                'verbose_name_plural': 'Мастер-пароли',
            },
        ),
    ]
