# Generated by Django 5.1.7 on 2025-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_masterpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpassword',
            name='is_revealed',
            field=models.BooleanField(default=False, verbose_name='Был ли мастер-пароль раскрыт'),
        ),
    ]
